sudo: required
services:
  - docker

before_install:
  - docker build -t elanvital80/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true elanvital80/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-556099210356"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACESS_KEY
  seret_access_key:
    secure: "$AWS_SECRET_KEY"
  